export const UPDATE = 'UPDATE';
export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';
export const TOGGLE_GAME_STARTED = 'TOGGLE_GAME_STARTED';
export const ADD_NEW_SHIP_PART = 'ADD_NEW_SHIP_PART';
export const SET_CURRENT_POSITION = 'SET_CURRENT_POSITION';
